Setup
dev89s/react-rails-hello pull request #1
Opened 2023-08-15 16:36 UTC by dev89s

In this PR:
1. Setup rails with webpack using `rails new -j webpack react-rails-hello`
2. Added `react` & `react-dom` to node-modules using `yarn add react react-dom`
3. Added `@babel/core`, `@babel/preset-env`, `@babel/preset-react`, & `bable-loader` through `yarn add @babel/core @babel/preset-env @babel/preset-react babel-loader --dev`
4. Added Bable config file declaring presets: `@babel/preset-env` & `@babel/preset-react`
5. Added babel loader to `webpack.config.js`:
```
  module: {
    rules: [
      {
        test: /\.(js)$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
    ],
  },
```
7. Added controller for Root of the project: `rails g controller Root index`
8. Configured the routing root to `root 'root#index'`
9. Created and migrated the database 
10. Ran the project with `./bin/dev` and tested to see if it works.
11. Created Redux store and greetings slice
12. Added React router, and made the Root Element
13. Created the backend API for getting a random greeting from the database
14. Created fetch function and an AsyncThunk to fetch and useEffect to dispatch the fetch.
15. Added the greeting to the component view

2023-08-15 17:05 UTC, mikethreels requested changes
Hi Sasan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-15 17:05 UTC, mikethreels commented on app/controllers/root_controller.rb
> +end
- [x] according to the requirements there should be a controller and a route for the random greeting as well.

2023-08-15 17:05 UTC, mikethreels commented on db/seeds.rb
> +#   Character.create(name: "Luke", movie: movies.first)
- [x] in order for this to work there should be a migration file for the greetings table.

2023-08-15 17:05 UTC, mikethreels commented on app/models/application_record.rb
> +end
- [x] the same as with the controller and the migration there should be a model to make this work correctly.

2023-08-15 17:05 UTC, mikethreels commented on app/javascript/controllers/application.js
> +export { application }
- [x] According to the requirements, in order for this to work correctly the below list should be implemented:
    - Create the App component with react-router and render it in your static view.
    - Create the Greeting component that will display a greeting. Set it up as a route in your App component.
    - Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
    - Display the random greeting in your Greeting component.

2023-08-16 22:07 UTC, Whoistolu commented on app/controllers/root_controller.rb
> +end
- Well resolved

2023-08-16 22:11 UTC, Whoistolu commented on db/seeds.rb
> +#   Character.create(name: "Luke", movie: movies.first)
- Well resolved

2023-08-16 22:13 UTC, Whoistolu commented on app/models/application_record.rb
> +end
- Well resolved

2023-08-16 22:18 UTC, Whoistolu commented on app/javascript/controllers/application.js
> +export { application }
- Well resolved

2023-08-16 22:19 UTC, Whoistolu approved these changes
### Hi @dev89s 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 08:54 UTC, merged